# CRE project settings — only local-simulation is needed for this example.
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://por.bcy-p.metalhosts.com/cre-alpha/MvqtrdftrbxcP3ZgGBJb3bK5/ethereum/sepolia
