name: smoke-test

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: zsh {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

          # Add it to /etc/shells if missing
          if ! grep -q "^$(which zsh)$" /etc/shells; then
            echo "$(which zsh)" | sudo tee -a /etc/shells
          fi

          # Change the default shell for the current user
          sudo chsh -s "$(which zsh)" $USER
        # Use bash or sh for this step, because zsh isn't set yet
        shell: bash {0}
      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Full checks
        run: bun full-checks
